// This file is autogenerated by the ToB build workflow. DO NOT EDIT

//! ## FSCKPad assembly
//! revision 1.1

THICKNESS = 1.6;
HEIGHT = 87.988061;
WIDTH = 173.391472;

MOUNTING_HOLES = [
        [ -56.75,48.25 ],
        [ -93.853,64.008 ],
        [ -41.75,63.25 ],
        [ -160.25,22.25 ],
        [ -16.75,22.25 ],
];

BOARD_POLY = [    [-77.913407,56.391852],
    [-77.495862,56.0265],
    [-70.73245,49.263088],
    [-71.748926,48.246613],
    [-71.739126,48.236813],
    [-72.849136,47.126803],
    [-80.978355,55.256023],
    [-80.947355,55.287543],
    [-80.948355,55.288543],
    [-83.140768,57.838309],
    [-84.919987,60.67006],
    [-86.259807,63.734258],
    [-87.134024,66.981369],
    [-92.692341,66.981369],
    [-92.253024,69.487172],
    [-92.124521,71.976703],
    [-92.299783,74.423343],
    [-92.771761,76.800475],
    [-93.533406,79.08148],
    [-94.577668,81.23974],
    [-95.897498,83.248639],
    [-97.485847,85.081557],
    [-98.92236,86.372663],
    [-100.478438,87.497999],
    [-102.141,88.452551],
    [-103.896962,89.231304],
    [-105.733243,89.829245],
    [-107.63676,90.241361],
    [-109.594431,90.462638],
    [-111.593173,90.488061],
    [-113.599204,90.315212],
    [-115.578473,89.949006],
    [-117.517493,89.395437],
    [-119.402777,88.660495],
    [-121.220838,87.750173],
    [-122.958189,86.670462],
    [-124.601343,85.427354],
    [-126.136812,84.026841],
    [-126.502162,83.609812],
    [-143.140942,66.971034],
    [-145.937723,66.811184],
    [-148.651295,66.382381],
    [-151.26824,65.697963],
    [-153.775145,64.771269],
    [-156.158592,63.615635],
    [-158.405167,62.244401],
    [-160.501453,60.670903],
    [-162.434036,58.908481],
    [-164.189499,56.970472],
    [-165.754426,54.870214],
    [-167.115403,52.621044],
    [-168.259012,50.236302],
    [-169.17184,47.729325],
    [-169.84047,45.113451],
    [-170.251485,42.402017],
    [-170.391472,39.608363],
    [-170.250228,36.801864],
    [-169.835559,34.078201],
    [-169.16106,31.450929],
    [-168.240325,28.933601],
    [-167.086951,26.53977],
    [-165.714531,24.282991],
    [-164.136661,22.176817],
    [-162.366934,20.234802],
    [-160.418948,18.470499],
    [-158.306295,16.897463],
    [-156.042572,15.529246],
    [-153.641372,14.379403],
    [-151.116292,13.461487],
    [-148.480925,12.789052],
    [-145.748867,12.375652],
    [-142.933712,12.23484],
    [-33.102745,12.234891],
    [-30.023895,12.404255],
    [-27.047493,12.900228],
    [-24.191012,13.704635],
    [-21.471927,14.799299],
    [-18.907709,16.166043],
    [-16.515833,17.786693],
    [-14.313773,19.64307],
    [-12.319,21.717],
    [-12.354657,22.93243],
    [-15.244404,25.948266],
    [-15.27541,25.895036],
    [-17.497496,28.117123],
    [-16.55416,29.623574],
    [-15.768244,31.195205],
    [-15.138526,32.821731],
    [-14.663781,34.492863],
    [-14.342787,36.198316],
    [-14.174319,37.927802],
    [-14.157155,39.671036],
    [-14.290071,41.417729],
    [-15.001248,44.880348],
    [-16.298063,48.233365],
    [-17.163025,49.843056],
    [-18.170726,51.394486],
    [-19.319943,52.877369],
    [-20.609451,54.281417],
    [-20.610451,54.282417],
    [-20.584091,54.309287],
    [-27.73766,61.463372],
    [-26.723251,62.47778],
    [-42.120761,77.874773],
    [-43.135169,76.860365],
    [-50.289255,84.01445],
    [-50.316125,83.9881],
    [-50.316642,83.988617],
    [-51.852159,85.389082],
    [-53.495355,86.632137],
    [-55.232742,87.711792],
    [-57.050834,88.622053],
    [-58.936142,89.356931],
    [-60.87518,89.910434],
    [-62.854461,90.276569],
    [-64.860496,90.449347],
    [-66.859235,90.423851],
    [-68.816896,90.202502],
    [-70.720396,89.790315],
    [-72.556653,89.192303],
    [-74.312585,88.413481],
    [-75.975109,87.458864],
    [-77.531144,86.333465],
    [-78.967607,85.042299],
    [-80.301684,83.554814],
    [-81.446626,81.959702],
    [-82.402963,80.271365],
    [-83.171226,78.504203],
    [-83.751943,76.672618],
    [-84.145645,74.791009],
    [-84.352862,72.873778],
    [-84.374124,70.935326],
    [-84.209959,68.990053],
    [-83.8609,67.052362],
    [-83.327474,65.136651],
    [-82.610213,63.257323],
    [-81.709646,61.428778],
    [-80.626302,59.665417],
    [-79.360713,57.981642],
];

//Position children at location of mounting holes
module position_pcb_mounts(){
    for (loc=MOUNTING_HOLES) {
        translate([loc[0], loc[1], 0]) children();
    }
}

module base_pcb(){
    difference(){
        color("green") linear_extrude(height=THICKNESS, convexity=20, center=true) polygon(BOARD_POLY);
        translate([-56.75,48.25,0]) cylinder(d=2.7, h=THICKNESS*2, center=true, $fn=14);
        translate([-93.853,64.008,0]) cylinder(d=2.7, h=THICKNESS*2, center=true, $fn=14);
        translate([-41.75,63.25,0]) cylinder(d=2.7, h=THICKNESS*2, center=true, $fn=14);
        translate([-160.25,22.25,0]) cylinder(d=2.7, h=THICKNESS*2, center=true, $fn=14);
        translate([-16.75,22.25,0]) cylinder(d=2.7, h=THICKNESS*2, center=true, $fn=14);
    }
}

module base_pcb_margin(){
    minkowski(){
        linear_extrude(height=THICKNESS, convexity=20, center=true) polygon(BOARD_POLY);
        cube([0.5, 0.5, 0.5], center=true);
    }
}

module base_pcb_clearance(upper=5, lower=5, wall_thickness=1.2){
    difference(){
        union(){
            translate([0,0,upper/2+THICKNESS/2]) linear_extrude(upper, convexity=20, center=true) offset(-wall_thickness) polygon(BOARD_POLY);
            translate([0,0,-lower/2-THICKNESS/2]) linear_extrude(lower, convexity=20, center=true) offset(-wall_thickness) polygon(BOARD_POLY);
        }
        position_pcb_mounts() cylinder(d=8, h=(upper+lower)*2+1, center=true, $fn=14);
    }
}

module position_Ext5(){
    //Position component Ext5 at location -98.25,17
    translate([-98.25,17, 0]) rotate([0,0,90]) children();
}
module position_XBOrient(){
    //Position component XBOrient at location -34.990369,70.165631
    translate([-34.990369,70.165631, 0]) rotate([0,0,45]) children();
}
module position_PSOrient(){
    //Position component PSOrient at location -64.260077,40.53913
    translate([-64.260077,40.53913, 0]) rotate([0,0,-135]) children();
}
module position_R2(){
    //Position component R2 at location -81.75,69.5
    translate([-81.75,69.5, 0]) rotate([0,0,-90]) children();
}
module position_Bite1(){
    //Position component Bite1 at location -17.783739,24.507261
    translate([-17.783739,24.507261, 0]) rotate([0,0,45]) children();
}
module position_RB1(){
    //Position component RB1 at location -132.5,13.9625
    translate([-132.5,13.9625, 0]) rotate([0,0,0]) children();
}
module position_H4(){
    //Position component H4 at location -56.75,48.25
    translate([-56.75,48.25, 0]) rotate([0,0,0]) children();
}
module position_H3(){
    //Position component H3 at location -93.853,64.008
    translate([-93.853,64.008, 0]) rotate([0,0,0]) children();
}
module position_C2(){
    //Position component C2 at location -95.24,39.0025
    translate([-95.24,39.0025, 0]) rotate([0,0,-90]) children();
}
module position_RTouch1(){
    //Position component RTouch1 at location -110.25,57
    translate([-110.25,57, 0]) rotate([0,0,0]) children();
}
module position_LRAEnable(){
    //Position component LRAEnable at location -62.992,16.4065
    translate([-62.992,16.4065, 0]) rotate([0,0,-90]) children();
}
module position_LTouch1(){
    //Position component LTouch1 at location -81.75,72.5
    translate([-81.75,72.5, 0]) rotate([0,0,0]) children();
}
module position_C1(){
    //Position component C1 at location -97.75,39.0025
    translate([-97.75,39.0025, 0]) rotate([0,0,-90]) children();
}
module position_Ext1(){
    //Position component Ext1 at location -78.994,49.911
    translate([-78.994,49.911, 0]) rotate([0,0,-135]) children();
}
module position_LRA_ERM1(){
    //Position component LRA/ERM1 at location -88.527,64.905
    translate([-88.527,64.905, 0]) rotate([0,0,0]) children();
}
module position_H5(){
    //Position component H5 at location -41.75,63.25
    translate([-41.75,63.25, 0]) rotate([0,0,0]) children();
}
module position_STEMMA_QT1(){
    //Position component STEMMA-QT1 at location -152.019,17.653
    translate([-152.019,17.653, 0]) rotate([0,0,157]) children();
}
module position_Y1(){
    //Position component Y1 at location -144.5,28.75
    translate([-144.5,28.75, 0]) rotate([0,0,180]) children();
}
module position_A1(){
    //Position component A1 at location -144.5,49.5
    translate([-144.5,49.5, 0]) rotate([0,0,180]) children();
}
module position_Start1(){
    //Position component Start1 at location -123.500892,22.225
    translate([-123.500892,22.225, 0]) rotate([0,0,0]) children();
}
module position_Mate(){
    //Position component Mate at location -64.252781,40.549965
    translate([-64.252781,40.549965, 0]) rotate([0,0,45]) children();
}
module position_LB1(){
    //Position component LB1 at location -41.475,13.7125
    translate([-41.475,13.7125, 0]) rotate([0,0,0]) children();
}
module position_H2(){
    //Position component H2 at location -160.25,22.25
    translate([-160.25,22.25, 0]) rotate([0,0,0]) children();
}
module position__plus_U1(){
    //Position component +U1 at location -33.25,30.25
    translate([-33.25,30.25, 0]) rotate([0,0,0]) children();
}
module position_Ext4(){
    //Position component Ext4 at location -128.349,13.716
    translate([-128.349,13.716, 0]) rotate([0,0,-90]) children();
}
module position_Bite2(){
    //Position component Bite2 at location -20.158447,26.062077
    translate([-20.158447,26.062077, 0]) rotate([0,0,45]) children();
}
module position__plus_L1(){
    //Position component +L1 at location -23.75,39.75
    translate([-23.75,39.75, 0]) rotate([0,0,0]) children();
}
module position__plus_D1(){
    //Position component +D1 at location -33.25,49.25
    translate([-33.25,49.25, 0]) rotate([0,0,0]) children();
}
module position_LS1(){
    //Position component LS1 at location -65.55,72.831281
    translate([-65.55,72.831281, 0]) rotate([0,0,90]) children();
}
module position_C3(){
    //Position component C3 at location -92.73,39.0025
    translate([-92.73,39.0025, 0]) rotate([0,0,-90]) children();
}
module position_Select1(){
    //Position component Select1 at location -53.546,22.098
    translate([-53.546,22.098, 0]) rotate([0,0,180]) children();
}
module position_IC3(){
    //Position component IC3 at location -88.5,39
    translate([-88.5,39, 0]) rotate([0,0,180]) children();
}
module position_POW1(){
    //Position component POW1 at location -88.5,56.769
    translate([-88.5,56.769, 0]) rotate([0,0,90]) children();
}
module position_X1(){
    //Position component X1 at location -132,39
    translate([-132,39, 0]) rotate([0,0,180]) children();
}
module position__plus_R1(){
    //Position component +R1 at location -42.75,39.75
    translate([-42.75,39.75, 0]) rotate([0,0,0]) children();
}
module position_RS1(){
    //Position component RS1 at location -110,73
    translate([-110,73, 0]) rotate([0,0,180]) children();
}
module position_R4(){
    //Position component R4 at location -86.4,43.08
    translate([-86.4,43.08, 0]) rotate([0,0,90]) children();
}
module position_R1(){
    //Position component R1 at location -114.1625,57
    translate([-114.1625,57, 0]) rotate([0,0,180]) children();
}
module position_H1(){
    //Position component H1 at location -16.75,22.25
    translate([-16.75,22.25, 0]) rotate([0,0,0]) children();
}
module position_EYESPI1(){
    //Position component EYESPI1 at location -88.5,16.05
    translate([-88.5,16.05, 0]) rotate([0,0,0]) children();
}
module position_B1(){
    //Position component B1 at location -156.5,39
    translate([-156.5,39, 0]) rotate([0,0,180]) children();
}
module position_R5(){
    //Position component R5 at location -91.92,46.36
    translate([-91.92,46.36, 0]) rotate([0,0,0]) children();
}
module position_C4(){
    //Position component C4 at location -87.471684,58.004136
    translate([-87.471684,58.004136, 0]) rotate([180,0,-90]) children();
}
module position_IC1(){
    //Position component IC1 at location -73.914,31.877
    translate([-73.914,31.877, 0]) rotate([180,0,90]) children();
}
module position_C5(){
    //Position component C5 at location -89.981684,58.004136
    translate([-89.981684,58.004136, 0]) rotate([180,0,-90]) children();
}
module position_LPDL1(){
    //Position component LPDL1 at location -49.25,55.75
    translate([-49.25,55.75, 0]) rotate([180,0,0]) children();
}
module position_IC5(){
    //Position component IC5 at location -113.792,19.177
    translate([-113.792,19.177, 0]) rotate([180,0,90]) children();
}
module position_Feather(){
    //Position component Feather at location -103.25,16.5
    translate([-103.25,16.5, 0]) rotate([180,0,180]) children();
}
module position_LT1(){
    //Position component LT1 at location -34.798,14.097
    translate([-34.798,14.097, 0]) rotate([180,0,180]) children();
}
module position_U1(){
    //Position component U1 at location -95.123,57.912
    translate([-95.123,57.912, 0]) rotate([180,0,180]) children();
}
module position_RPDL1(){
    //Position component RPDL1 at location -127.5,55.5
    translate([-127.5,55.5, 0]) rotate([180,0,0]) children();
}
module position_IC4(){
    //Position component IC4 at location -72.517,19.05
    translate([-72.517,19.05, 0]) rotate([180,0,90]) children();
}
module position_Centroid1(){
    //Position component Centroid1 at location -88.646,40.64
    translate([-88.646,40.64, 0]) rotate([180,0,180]) children();
}
module position_RT1(){
    //Position component RT1 at location -145.796,14.059
    translate([-145.796,14.059, 0]) rotate([180,0,180]) children();
}
module position_IC6(){
    //Position component IC6 at location -112.522,31.75
    translate([-112.522,31.75, 0]) rotate([180,0,90]) children();
}
if($preview)
    //base_pcb();
    //%base_pcb_clearance();
    %base_pcb_margin();